version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "yx05!#5YV!CZQ0s0"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  neo4j:
    image: neo4j:5-community
    container_name: neo4j
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042" # CQL native transport
    environment:
      - CASSANDRA_CLUSTER_NAME=eduscale_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    container_name: instituciones-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - neo4j
      - cassandra
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:yx05%21%235YV%21CZQ0s0@mongodb:27018/eduscale?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - ENROLLMENT_RESERVATION_TTL=900
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=eduscale_scholarships
      - CASSANDRA_DC=datacenter1
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
  cassandra_data:
